### ISSUE TITLE
Dependency not found

### ISSUE THREAD

**Issue by aematsubara** [PZDonny/DisplayEntityUtils#7]
Hi, for some reason my pom.xml can't find the dependency (the one listed on the readme). Am I missing a repository?
I tried using jitpack too but the result is BUILD FAILURE.

My pom: https://pastebin.com/pV44kfvb

**Comment by PZDonny** [comment]
Hi, sorry for the long wait. I've fixed this issue [here](https://github.com/PZDonny/DisplayEntityUtils/releases/tag/2.4.1). If you have any issues please let me know and I'll get them fixed asap.

**Comment by aematsubara** [comment]
No problem, thanks!

It's working now, however the dependency should be changed from:

```
<dependency>
            <groupId>net.donnypz</groupId>
            <artifactId>displayentityutils</artifactId>
            <version>2.4.1</version>
            <scope>provided</scope>
</dependency>
```

to

```
<dependency>
            <groupId>com.github.PZDonny</groupId>
            <artifactId>DisplayEntityUtils</artifactId>
            <version>2.4.1</version>
            <scope>provided</scope>
</dependency>
```

**Comment by PZDonny** [comment]
Thanks for letting me know, I'll change that now
